### PR TITLE
Features: anti flicker hint.

### PR DESCRIPTION
**Pull request by vrishe**
There is a problem with ImageLoader's displayImage set of methods: https://github.com/nostra13/Android-Universal-Image-Loader/issues/376. And here is an extremely simple of possible solutions. At least me and my colleague gave it a try and this solution has satisfied us both. 

In short:
The source of flickering is the complete display cycle even in that case when a particular image resides in memory cache. So, we have just added a simple hint, called short pipeline, that prevents posting ProcessAndDisplayImageTask on handler's queue and runs it directly. This is almost the same with syncLoading approach , but again, only if we have an image in memory cache. 

P.S.: Please, give it a look. There's an additional 'Invalidate data set' item was introduced within the sample application, also. Look for 'Invalidate data set' item in menu, which will help users to check this hint is working.

### CODE REVIEW

**Comment by nostra13** [comment]
I don't see any place where you use `shortPipeline(true)` so I can't understand how a user should use it and how it can be useful.

**Comment by vrishe** [comment]
Oh, sorry. Haven't mentioned that it is set to `true` by default currently (please, see library/src/.../core/DisplayImageOptions.java, line 227).

In our practice the flicker comes in to play with time: I mean when project gets more complicated, and more work has to be performed on the main thread then. This means, we start having more tasks on the main thread's queue at a time (aside from those tasks ImageLoader facility posts to). Thus, without this flag we have a longer delay between calls to ImageLoader's displayImage(...) and ProcessAndDisplayImageTask's run() methods.

**Comment by nostra13** [comment]
You use `postProcessor(...)`, right? And you want to do PostProcessor execution on Main thread using "short pipeline"?

**Comment by vrishe** [comment]
Not exactly, I want to make the whole `ProcessAndDisplayImageTask` to be run on the UI thread in that case if `options.isShortPipeline()` flag was set (please, refer to line 246 of ImageLoader.java implementation here: vrishe/Android-Universal-Image-Loader@6f36076).

Also, a small adjustment was made within the execution flow of the `ProcessAndDisplayTask.run()` method: we're now have to check whether a custom handler was assigned to perform a `DisplayBitmapTask` (please, look at line 57 of ProcessAndDisplayTask.java implementation, following the same link as specified above).

--
Obviously, it makes us to avoid the use of heavyweight post-processing routines along with this so-called `shortPipeline` mode enabled. But it will be repaid with much faster image delivery to a certain viewport during the bulk updates of data set.

**Comment by nostra13** [comment]
I think you can use `BitmapDisplayer` instead of `BitmapProcessor` to avoid "post-processing routines". `BitmapDisplayer` is executed on UI thread so you just need to add something like `imageView.setImageBitmap(bitmap)` in the end at `display(...)` method.

**Comment by vrishe** [comment]
That's it! I haven't taken even a small look here: `if (options.shouldPostProcess()) { ... }` before doing my changes. So all these changes are unnecessary, I close the request.

**Pull request closed without merging**
