### PR TITLE
Added gradle build scripts

### PR DESCRIPTION
**Pull request by jitpack-io**
Hi!

Added gradle buildscripts by translating the maven poms. 
Upload to maven central is based on these instructions: https://github.com/chrisbanes/gradle-mvn-push

Travis seems happy so hopefully nothing's missing.

### CODE REVIEW

**Comment by nostra13** [comment]
Thanks!

**Comment by jitpack-io** [comment]
Great! In case of any issues give me a shout.
Btw, saw that your releases go on Maven Central. Would you be at all interested in serving snapshot releases from jitpack.io?

**Comment by nostra13** [comment]
That would be great)

**Comment by jitpack-io** [comment]
Nice. Should be straightforward after this PR. Will submit a PR with dependency info

**Comment by nostra13** [comment]
Thanks.

**Comment by jitpack-io** [comment]
@nostra13 Submitted in #998

**Pull request merged**
