### PR TITLE
Base64 support

### PR DESCRIPTION
**Pull request by mrleolink**
Supports Base64 images.

### CODE REVIEW

**Comment by mrleolink** [comment]
Yeah, this is not actually "scheme" but people are using it a lot in websites, so would you like to support it?

**Comment by nostra13** [comment]
I understand but this is for some consistency in UIL. It will be not hard to pass `"base64://" + base64` into ImageLoader. ImageLoader will do the rest.

**Comment by mrleolink** [comment]
I just fixed it, maybe it's better but users will have to add `base64://` prefix by their own :)

**Comment by nostra13** [comment]
Decided not include Base64 support out the box. Created Base64ImageDownloader to support it in **ext** package. 562500747f8d6942bbe68937e8ba8ebf0d04a278

**Pull request closed without merging**
