### PR TITLE
Fix bug OkHttpImageDownloader reports wrong values to ImageLoadingProgressListener

### PR DESCRIPTION
**Pull request by mrleolink**
Support contentLength for OkHttp, so ImageLoadingProgressListener's onProgressUpdate will report correct values

### CODE REVIEW

**Comment by nostra13** [comment]
Right, but it doesn't compiles. Missed imports, I guess.

**Comment by mrleolink** [comment]
Oh, so I should make another pull request?

**Comment by mrleolink** [comment]
By the way, you should make this library supports data image base64 which has format like "data:image/png....". Currently, I'm overriding the method `getStreamFromOtherSource` to get it work but it would be nicer if you add one more scheme in `BaseImageDownloader`

**Comment by nostra13** [comment]
> Oh, so I should make another pull request?

You can update this PR, I think.
You can create PR about Base64 too, or you can share your code about it. I'll look int it.

**Comment by mrleolink** [comment]
I added missed import, so it compiles now.

I also created a PR for base64 support, please take a look.

**Comment by nostra13** [comment]
Great, thanks.

**Pull request merged**
